"""add_nutrition_label_column

Revision ID: 416d79950906
Revises: 395f9b36eaac
Create Date: 2026-04-08 17:58:35.118023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '416d79950906'
down_revision: Union[str, None] = '395f9b36eaac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_analysis_results', sa.Column('nutrition_label', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_user_favorites_document_id', table_name='user_favorites')
    op.create_index(op.f('ix_user_favorites_global_document_id'), 'user_favorites', ['global_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorites_global_document_id'), table_name='user_favorites')
    op.create_index('ix_user_favorites_document_id', 'user_favorites', ['global_document_id'], unique=False)
    op.drop_column('global_analysis_results', 'nutrition_label')
    # ### end Alembic commands ###
